version: "3"
services:
    web:
        build: .
        container_name: php73
        depends_on: 
            - db
        volumes:
          - ./php:/var/www/html/

        ports:
          - 8000:80

    db:
        container_name: mysql8
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABSE: test_db
            MYSQL_USER: devuser
            MYSQL_PASSWORD: devpass
        ports:
            - 3306:3306 
